insert into productos (nombre_producto, precio) values ('Coffee Cup 8oz 5338cd', 683.3);
insert into productos (nombre_producto, precio) values ('Bread - Bistro Sour', 806.27);
insert into productos (nombre_producto, precio) values ('Pastry - Key Limepoppy Seed Tea', 93.41);
insert into productos (nombre_producto, precio) values ('Appetizer - Assorted Box', 632.29);
insert into productos (nombre_producto, precio) values ('Soup Bowl Clear 8oz92008', 537.54);
insert into productos (nombre_producto, precio) values ('Tea Peppermint', 465.2);
insert into productos (nombre_producto, precio) values ('Filling - Mince Meat', 816.64);
insert into productos (nombre_producto, precio) values ('Lettuce - Baby Salad Greens', 643.6);
insert into productos (nombre_producto, precio) values ('Longos - Assorted Sandwich', 789.64);
insert into productos (nombre_producto, precio) values ('Coffee Guatemala Dark', 532.33);
insert into productos (nombre_producto, precio) values ('Steampan Lid', 370.18);
insert into productos (nombre_producto, precio) values ('Chevril', 228.85);
insert into productos (nombre_producto, precio) values ('Cheese - Goat With Herbs', 431.29);
insert into productos (nombre_producto, precio) values ('Chicken - Breast, 5 - 7 Oz', 252.37);
insert into productos (nombre_producto, precio) values ('Chocolate - White', 910.37);
insert into productos (nombre_producto, precio) values ('Pepper - Red Thai', 935.11);
insert into productos (nombre_producto, precio) values ('Mcgillicuddy Vanilla Schnap', 289.5);
insert into productos (nombre_producto, precio) values ('Beets - Pickled', 833.04);
insert into productos (nombre_producto, precio) values ('Grapes - Green', 792.4);
insert into productos (nombre_producto, precio) values ('Bagel - Ched Chs Presliced', 696.06);
insert into productos (nombre_producto, precio) values ('Muffin - Mix - Bran And Maple 15l', 854.38);
insert into productos (nombre_producto, precio) values ('Jam - Strawberry, 20 Ml Jar', 648.49);
insert into productos (nombre_producto, precio) values ('Table Cloth 54x72 Colour', 125.48);
insert into productos (nombre_producto, precio) values ('Cheese - Bakers Cream Cheese', 654.43);
insert into productos (nombre_producto, precio) values ('Juice - Ocean Spray Cranberry', 937.97);
insert into productos (nombre_producto, precio) values ('Onions - Red', 413.79);
insert into productos (nombre_producto, precio) values ('Cheese - Ricotta', 789.26);
insert into productos (nombre_producto, precio) values ('Wine - Shiraz South Eastern', 456.47);
insert into productos (nombre_producto, precio) values ('Ecolab - Medallion', 295.24);
insert into productos (nombre_producto, precio) values ('Energy Drink - Franks Original', 494.89);
insert into productos (nombre_producto, precio) values ('Bread - Roll, Italian', 142.11);
insert into productos (nombre_producto, precio) values ('Container - Clear 16 Oz', 437.13);
insert into productos (nombre_producto, precio) values ('Sugar - White Packet', 279.94);
insert into productos (nombre_producto, precio) values ('Rice Paper', 529.51);
insert into productos (nombre_producto, precio) values ('Strawberries - California', 750.43);
insert into productos (nombre_producto, precio) values ('Muffin - Carrot Individual Wrap', 518.48);
insert into productos (nombre_producto, precio) values ('Isomalt', 571.7);
insert into productos (nombre_producto, precio) values ('Beef - Top Sirloin', 183.82);
insert into productos (nombre_producto, precio) values ('Swordfish Loin Portions', 250.39);
insert into productos (nombre_producto, precio) values ('Wine - Manischewitz Concord', 123.17);
insert into productos (nombre_producto, precio) values ('Cookie Dough - Peanut Butter', 227.39);
insert into productos (nombre_producto, precio) values ('White Fish - Filets', 780.93);
insert into productos (nombre_producto, precio) values ('Wine - Alsace Gewurztraminer', 688.59);
insert into productos (nombre_producto, precio) values ('Wine - Chateau Bonnet', 333.39);
insert into productos (nombre_producto, precio) values ('Wine - Shiraz Wolf Blass Premium', 812.85);
insert into productos (nombre_producto, precio) values ('Wine - White, Pinot Grigio', 837.57);
insert into productos (nombre_producto, precio) values ('Cheese - Stilton', 641.94);
insert into productos (nombre_producto, precio) values ('Ecolab - Balanced Fusion', 134.73);
insert into productos (nombre_producto, precio) values ('Neckerchief Blck', 268.19);
insert into productos (nombre_producto, precio) values ('Ice Cream - Fudge Bars', 206.54);
insert into productos (nombre_producto, precio) values ('Brandy - Orange, Mc Guiness', 550.01);
insert into productos (nombre_producto, precio) values ('Pork - Loin, Boneless', 58.57);
insert into productos (nombre_producto, precio) values ('Cardamon Seed / Pod', 158.29);
insert into productos (nombre_producto, precio) values ('Crab - Blue, Frozen', 420.62);
insert into productos (nombre_producto, precio) values ('Mushroom - Shitake, Fresh', 661.76);
insert into productos (nombre_producto, precio) values ('Gingerale - Diet - Schweppes', 288.41);
insert into productos (nombre_producto, precio) values ('Oil - Avocado', 261.91);
insert into productos (nombre_producto, precio) values ('Lobster - Canned Premium', 278.35);
insert into productos (nombre_producto, precio) values ('Quail - Jumbo Boneless', 557.65);
insert into productos (nombre_producto, precio) values ('Cheese Cloth No 60', 863.45);
insert into productos (nombre_producto, precio) values ('Wasabi Paste', 947.69);
insert into productos (nombre_producto, precio) values ('Cake - Dulce De Leche', 410.29);
insert into productos (nombre_producto, precio) values ('Coffee Cup 12oz 5342cd', 784.68);
insert into productos (nombre_producto, precio) values ('Soup - Chicken And Wild Rice', 363.04);
insert into productos (nombre_producto, precio) values ('Fireball Whisky', 313.05);
insert into productos (nombre_producto, precio) values ('Wine - White, Schroder And Schyl', 946.0);
insert into productos (nombre_producto, precio) values ('Wine - Red Oakridge Merlot', 434.68);
insert into productos (nombre_producto, precio) values ('Bread Foccacia Whole', 232.2);
insert into productos (nombre_producto, precio) values ('Sesame Seed', 693.45);
insert into productos (nombre_producto, precio) values ('Wine - Magnotta - Belpaese', 503.45);
insert into productos (nombre_producto, precio) values ('Cookies - Englishbay Wht', 16.7);
insert into productos (nombre_producto, precio) values ('Oil - Coconut', 455.58);
insert into productos (nombre_producto, precio) values ('Nestea - Iced Tea', 391.94);
insert into productos (nombre_producto, precio) values ('Soup - Cream Of Broccoli', 160.5);
insert into productos (nombre_producto, precio) values ('Wine - Chateau Aqueria Tavel', 652.63);
insert into productos (nombre_producto, precio) values ('Cheese - Brie,danish', 422.93);
insert into productos (nombre_producto, precio) values ('Beef - Cooked, Corned', 523.3);
insert into productos (nombre_producto, precio) values ('Wine - White Cab Sauv.on', 93.32);
insert into productos (nombre_producto, precio) values ('Coffee - Irish Cream', 141.65);
insert into productos (nombre_producto, precio) values ('Honey - Liquid', 932.6);
insert into productos (nombre_producto, precio) values ('Taro Root', 71.08);
insert into productos (nombre_producto, precio) values ('Ranchero - Primerba, Paste', 569.04);
insert into productos (nombre_producto, precio) values ('Water - Tonic', 306.32);
insert into productos (nombre_producto, precio) values ('Muffin Mix - Banana Nut', 273.07);
insert into productos (nombre_producto, precio) values ('Chutney Sauce - Mango', 460.24);
insert into productos (nombre_producto, precio) values ('Sauce - Ranch Dressing', 168.9);
insert into productos (nombre_producto, precio) values ('Marjoram - Fresh', 504.16);
insert into productos (nombre_producto, precio) values ('Cherries - Frozen', 191.7);
insert into productos (nombre_producto, precio) values ('Heavy Duty Dust Pan', 589.7);
insert into productos (nombre_producto, precio) values ('Sweet Pea Sprouts', 665.98);
insert into productos (nombre_producto, precio) values ('Duck - Fat', 15.02);
insert into productos (nombre_producto, precio) values ('Fireball Whisky', 334.55);
insert into productos (nombre_producto, precio) values ('Quail Eggs - Canned', 7.81);
insert into productos (nombre_producto, precio) values ('Mustard - Pommery', 558.91);
insert into productos (nombre_producto, precio) values ('Flour - Whole Wheat', 359.37);
insert into productos (nombre_producto, precio) values ('Tamarillo', 189.51);
insert into productos (nombre_producto, precio) values ('Sugar Thermometer', 552.52);
insert into productos (nombre_producto, precio) values ('Glass - Juice Clear 5oz 55005', 959.26);
insert into productos (nombre_producto, precio) values ('Cake - Sheet Strawberry', 536.04);
insert into productos (nombre_producto, precio) values ('Onions - Spanish', 266.34);
insert into productos (nombre_producto, precio) values ('Potatoes - Mini White 3 Oz', 464.65);
insert into productos (nombre_producto, precio) values ('Soup - Beef, Base Mix', 463.42);
insert into productos (nombre_producto, precio) values ('Grenadillo', 231.07);
insert into productos (nombre_producto, precio) values ('Salmon - Sockeye Raw', 996.45);
insert into productos (nombre_producto, precio) values ('Tomato - Plum With Basil', 912.67);
insert into productos (nombre_producto, precio) values ('Wine - Chablis 2003 Champs', 208.5);
insert into productos (nombre_producto, precio) values ('Juice - Orange, 341 Ml', 790.9);
insert into productos (nombre_producto, precio) values ('Pasta - Linguini, Dry', 844.7);
insert into productos (nombre_producto, precio) values ('Pea - Snow', 294.66);
insert into productos (nombre_producto, precio) values ('Durian Fruit', 13.96);
insert into productos (nombre_producto, precio) values ('Bread - Italian Roll With Herbs', 833.99);
insert into productos (nombre_producto, precio) values ('Goulash Seasoning', 128.37);
insert into productos (nombre_producto, precio) values ('Eggplant - Asian', 239.79);
insert into productos (nombre_producto, precio) values ('Shrimp - Black Tiger 6 - 8', 835.22);
insert into productos (nombre_producto, precio) values ('Glass Clear 8 Oz', 30.28);
insert into productos (nombre_producto, precio) values ('Beef - Cow Feet Split', 270.43);
insert into productos (nombre_producto, precio) values ('Sobe - Tropical Energy', 923.37);
insert into productos (nombre_producto, precio) values ('Pork - Backfat', 122.34);
insert into productos (nombre_producto, precio) values ('Egg - Salad Premix', 393.11);
insert into productos (nombre_producto, precio) values ('Tahini Paste', 213.53);
insert into productos (nombre_producto, precio) values ('Beans - Fine', 991.97);
insert into productos (nombre_producto, precio) values ('Trout - Hot Smkd, Dbl Fillet', 937.38);
insert into productos (nombre_producto, precio) values ('Mustard Prepared', 355.07);
insert into productos (nombre_producto, precio) values ('Napkin Colour', 37.17);
insert into productos (nombre_producto, precio) values ('Bag - Clear 7 Lb', 88.74);
insert into productos (nombre_producto, precio) values ('Hog / Sausage Casing - Pork', 726.5);
insert into productos (nombre_producto, precio) values ('Container - Clear 32 Oz', 977.06);
insert into productos (nombre_producto, precio) values ('Beer - Upper Canada Light', 124.7);
insert into productos (nombre_producto, precio) values ('Apron', 81.29);
insert into productos (nombre_producto, precio) values ('Lemonade - Natural, 591 Ml', 827.49);
insert into productos (nombre_producto, precio) values ('Appetizer - Crab And Brie', 128.84);
insert into productos (nombre_producto, precio) values ('Asparagus - Mexican', 552.78);
insert into productos (nombre_producto, precio) values ('Pepper - Jalapeno', 48.93);
insert into productos (nombre_producto, precio) values ('Lamb - Leg, Boneless', 240.99);
insert into productos (nombre_producto, precio) values ('Mix - Cocktail Ice Cream', 41.51);
insert into productos (nombre_producto, precio) values ('Pepper - Green, Chili', 958.33);
insert into productos (nombre_producto, precio) values ('Olives - Green, Pitted', 448.27);
insert into productos (nombre_producto, precio) values ('Bread - Crusty Italian Poly', 857.53);
insert into productos (nombre_producto, precio) values ('Bag Clear 10 Lb', 412.62);
insert into productos (nombre_producto, precio) values ('Doilies - 10, Paper', 919.45);
insert into productos (nombre_producto, precio) values ('Sugar - Invert', 519.13);
insert into productos (nombre_producto, precio) values ('Wine - Penfolds Koonuga Hill', 248.16);
insert into productos (nombre_producto, precio) values ('Soup - Campbells Chili Veg', 369.89);
insert into productos (nombre_producto, precio) values ('Swiss Chard', 376.71);
insert into productos (nombre_producto, precio) values ('Goldschalger', 821.06);
insert into productos (nombre_producto, precio) values ('Wine - Magnotta - Cab Sauv', 72.33);
insert into productos (nombre_producto, precio) values ('Rosemary - Primerba, Paste', 361.03);
insert into productos (nombre_producto, precio) values ('Chocolate - Pistoles, Lactee, Milk', 587.98);
insert into productos (nombre_producto, precio) values ('Soup - Base Broth Beef', 492.19);
insert into productos (nombre_producto, precio) values ('Mushroom - Chantrelle, Fresh', 825.86);
insert into productos (nombre_producto, precio) values ('Coriander - Seed', 359.04);
insert into productos (nombre_producto, precio) values ('Lemonade - Pineapple Passion', 168.14);
insert into productos (nombre_producto, precio) values ('Flour - Semolina', 710.48);
insert into productos (nombre_producto, precio) values ('Nantuket Peach Orange', 901.22);
insert into productos (nombre_producto, precio) values ('Sauce - Soya, Dark', 19.53);
insert into productos (nombre_producto, precio) values ('Bread - Crusty Italian Poly', 38.62);
insert into productos (nombre_producto, precio) values ('Beef - Prime Rib Aaa', 51.26);
insert into productos (nombre_producto, precio) values ('Bag - Bread, White, Plain', 473.76);
insert into productos (nombre_producto, precio) values ('Tea - Mint', 563.21);
insert into productos (nombre_producto, precio) values ('Puree - Raspberry', 899.62);
insert into productos (nombre_producto, precio) values ('Pineapple - Regular', 794.37);
insert into productos (nombre_producto, precio) values ('V8 - Vegetable Cocktail', 45.69);
insert into productos (nombre_producto, precio) values ('Dawn Professionl Pot And Pan', 450.16);
insert into productos (nombre_producto, precio) values ('Sobe - Green Tea', 539.94);
insert into productos (nombre_producto, precio) values ('Pomegranates', 71.3);
insert into productos (nombre_producto, precio) values ('Pasta - Cheese / Spinach Bauletti', 858.27);
insert into productos (nombre_producto, precio) values ('Lobster - Tail, 3 - 4 Oz', 178.81);
insert into productos (nombre_producto, precio) values ('External Supplier', 988.67);
insert into productos (nombre_producto, precio) values ('Brandy Apricot', 25.82);
insert into productos (nombre_producto, precio) values ('Truffle Cups Green', 603.42);
insert into productos (nombre_producto, precio) values ('Pork - Sausage Casing', 130.97);
insert into productos (nombre_producto, precio) values ('Wine - Magnotta - Cab Sauv', 776.95);
insert into productos (nombre_producto, precio) values ('Butter - Pod', 20.88);
insert into productos (nombre_producto, precio) values ('Wine - Blue Nun Qualitatswein', 327.39);
insert into productos (nombre_producto, precio) values ('Peach - Halves', 284.0);
insert into productos (nombre_producto, precio) values ('Squash - Pattypan, Yellow', 270.04);
insert into productos (nombre_producto, precio) values ('Sun - Dried Tomatoes', 888.01);
insert into productos (nombre_producto, precio) values ('Pumpkin - Seed', 596.39);
insert into productos (nombre_producto, precio) values ('Bread - Mini Hamburger Bun', 154.78);
insert into productos (nombre_producto, precio) values ('Cattail Hearts', 427.75);
insert into productos (nombre_producto, precio) values ('Tomatoes - Hot House', 879.38);
insert into productos (nombre_producto, precio) values ('Bread Cranberry Foccacia', 689.33);
insert into productos (nombre_producto, precio) values ('Chocolate - Milk, Callets', 704.72);
insert into productos (nombre_producto, precio) values ('Champagne - Brights, Dry', 276.09);
insert into productos (nombre_producto, precio) values ('Bread - Olive', 7.67);
insert into productos (nombre_producto, precio) values ('Foil - Round Foil', 111.44);
insert into productos (nombre_producto, precio) values ('Wine - Hardys Bankside Shiraz', 593.16);
insert into productos (nombre_producto, precio) values ('Sprouts - China Rose', 288.76);
insert into productos (nombre_producto, precio) values ('Vinegar - Champagne', 557.39);
insert into productos (nombre_producto, precio) values ('Madeira', 983.75);
insert into productos (nombre_producto, precio) values ('Sour Puss Raspberry', 719.47);
insert into productos (nombre_producto, precio) values ('Beets', 439.06);
insert into productos (nombre_producto, precio) values ('Chicken Breast Halal', 686.83);
insert into productos (nombre_producto, precio) values ('Wine - Niagara,vqa Reisling', 693.06);
insert into productos (nombre_producto, precio) values ('Piping - Bags Quizna', 998.79);
insert into productos (nombre_producto, precio) values ('Cake - Dulce De Leche', 844.75);
insert into productos (nombre_producto, precio) values ('Ecolab Crystal Fusion', 603.97);
insert into productos (nombre_producto, precio) values ('Energy Drink Red Bull', 812.58);
insert into productos (nombre_producto, precio) values ('Cheese - Asiago', 441.47);
insert into productos (nombre_producto, precio) values ('Mangostein', 285.35);
insert into productos (nombre_producto, precio) values ('Veal - Kidney', 688.33);
insert into productos (nombre_producto, precio) values ('Sauce - Demi Glace', 816.96);
insert into productos (nombre_producto, precio) values ('Foam Dinner Plate', 478.34);
insert into productos (nombre_producto, precio) values ('Shrimp - Black Tiger 26/30', 637.37);
insert into productos (nombre_producto, precio) values ('Puree - Guava', 309.06);
insert into productos (nombre_producto, precio) values ('Tea - Lemon Scented', 513.88);
insert into productos (nombre_producto, precio) values ('Bread - Malt', 190.04);
insert into productos (nombre_producto, precio) values ('Pie Pecan', 69.07);
insert into productos (nombre_producto, precio) values ('Appetizer - Sausage Rolls', 825.52);
insert into productos (nombre_producto, precio) values ('Pails With Lids', 172.99);
insert into productos (nombre_producto, precio) values ('Bread - Italian Corn Meal Poly', 266.9);
insert into productos (nombre_producto, precio) values ('Fish - Atlantic Salmon, Cold', 329.13);
insert into productos (nombre_producto, precio) values ('Soup - Base Broth Beef', 464.39);
insert into productos (nombre_producto, precio) values ('Juice Peach Nectar', 423.23);
insert into productos (nombre_producto, precio) values ('Stock - Veal, Brown', 226.61);
insert into productos (nombre_producto, precio) values ('Raspberries - Fresh', 645.98);
insert into productos (nombre_producto, precio) values ('Salmon Atl.whole 8 - 10 Lb', 823.92);
insert into productos (nombre_producto, precio) values ('Sobe - Green Tea', 987.12);
insert into productos (nombre_producto, precio) values ('Milk Powder', 550.27);
insert into productos (nombre_producto, precio) values ('Flour Dark Rye', 53.88);
insert into productos (nombre_producto, precio) values ('Salmon - Atlantic, No Skin', 232.02);
insert into productos (nombre_producto, precio) values ('Beef - Baby, Liver', 907.47);
insert into productos (nombre_producto, precio) values ('Pate - Liver', 777.64);
insert into productos (nombre_producto, precio) values ('Muffin Chocolate Individual Wrap', 645.41);
insert into productos (nombre_producto, precio) values ('Bread - Wheat Baguette', 74.64);
insert into productos (nombre_producto, precio) values ('Pork - Ham Hocks - Smoked', 199.12);
insert into productos (nombre_producto, precio) values ('Wonton Wrappers', 842.09);
insert into productos (nombre_producto, precio) values ('Lettuce - Radicchio', 788.9);
insert into productos (nombre_producto, precio) values ('Bread - Italian Sesame Poly', 669.65);
insert into productos (nombre_producto, precio) values ('Sprite - 355 Ml', 277.23);
insert into productos (nombre_producto, precio) values ('Crawfish', 841.26);
insert into productos (nombre_producto, precio) values ('Wine - Lamancha Do Crianza', 324.0);
insert into productos (nombre_producto, precio) values ('Gelatine Leaves - Envelopes', 988.44);
insert into productos (nombre_producto, precio) values ('Burger Veggie', 58.1);
insert into productos (nombre_producto, precio) values ('Extract - Almond', 66.78);
insert into productos (nombre_producto, precio) values ('Sprouts - Alfalfa', 245.39);
insert into productos (nombre_producto, precio) values ('Iced Tea Concentrate', 837.44);
insert into productos (nombre_producto, precio) values ('Mix - Cocktail Ice Cream', 628.1);
insert into productos (nombre_producto, precio) values ('Chinese Lemon Pork', 162.88);
insert into productos (nombre_producto, precio) values ('Cake Circle, Foil, Scallop', 279.56);
insert into productos (nombre_producto, precio) values ('Lid Coffee Cup 8oz Blk', 221.18);
insert into productos (nombre_producto, precio) values ('Bread - Dark Rye', 901.5);
insert into productos (nombre_producto, precio) values ('Cookie - Dough Variety', 243.12);
insert into productos (nombre_producto, precio) values ('Veal - Osso Bucco', 17.49);
insert into productos (nombre_producto, precio) values ('Muffin Mix - Corn Harvest', 884.0);
insert into productos (nombre_producto, precio) values ('Temperature Recording Station', 942.73);
insert into productos (nombre_producto, precio) values ('True - Vue Containers', 759.57);
insert into productos (nombre_producto, precio) values ('Juice - Orangina', 771.44);
insert into productos (nombre_producto, precio) values ('Beef - Chuck, Boneless', 730.47);
insert into productos (nombre_producto, precio) values ('Pepper - Roasted Red', 700.47);
insert into productos (nombre_producto, precio) values ('Godiva White Chocolate', 584.21);
insert into productos (nombre_producto, precio) values ('Bananas', 272.03);
insert into productos (nombre_producto, precio) values ('Vinegar - Raspberry', 335.17);
insert into productos (nombre_producto, precio) values ('Broom And Broom Rack White', 255.17);
insert into productos (nombre_producto, precio) values ('Table Cloth 62x114 Colour', 444.03);
insert into productos (nombre_producto, precio) values ('Peppercorns - Pink', 709.42);
insert into productos (nombre_producto, precio) values ('Tuna - Yellowfin', 314.64);
insert into productos (nombre_producto, precio) values ('Grapefruit - White', 169.01);
insert into productos (nombre_producto, precio) values ('Beets - Candy Cane, Organic', 19.79);
insert into productos (nombre_producto, precio) values ('Potatoes - Peeled', 855.58);
insert into productos (nombre_producto, precio) values ('Muffin - Bran Ind Wrpd', 224.38);
insert into productos (nombre_producto, precio) values ('Vinegar - Red Wine', 545.61);
insert into productos (nombre_producto, precio) values ('Bread - Italian Roll With Herbs', 364.91);
insert into productos (nombre_producto, precio) values ('Chocolate - White', 812.62);
insert into productos (nombre_producto, precio) values ('Wine - Chardonnay Mondavi', 80.25);
insert into productos (nombre_producto, precio) values ('Chocolate - Unsweetened', 9.39);
insert into productos (nombre_producto, precio) values ('Pasta - Angel Hair', 965.78);
insert into productos (nombre_producto, precio) values ('Bag - Regular Kraft 20 Lb', 78.8);
insert into productos (nombre_producto, precio) values ('Chocolate - Semi Sweet, Calets', 336.25);
insert into productos (nombre_producto, precio) values ('Bar Mix - Lemon', 2.87);
insert into productos (nombre_producto, precio) values ('Wine - Domaine Boyar Royal', 195.62);
insert into productos (nombre_producto, precio) values ('Icecream - Dstk Cml And Fdg', 368.79);
insert into productos (nombre_producto, precio) values ('Juice - Prune', 396.85);
insert into productos (nombre_producto, precio) values ('Shallots', 735.14);
insert into productos (nombre_producto, precio) values ('Water - Mineral, Natural', 539.05);
insert into productos (nombre_producto, precio) values ('Pepper - Orange', 770.99);
insert into productos (nombre_producto, precio) values ('Lamb - Whole, Fresh', 333.41);
insert into productos (nombre_producto, precio) values ('Cheese - Sheep Milk', 925.84);
insert into productos (nombre_producto, precio) values ('Sandwich Wrap', 622.22);
insert into productos (nombre_producto, precio) values ('Juice - Lagoon Mango', 12.44);
insert into productos (nombre_producto, precio) values ('Liqueur Banana, Ramazzotti', 321.4);
insert into productos (nombre_producto, precio) values ('Cream Of Tartar', 119.48);
insert into productos (nombre_producto, precio) values ('Sprite - 355 Ml', 79.72);
insert into productos (nombre_producto, precio) values ('Lemonade - Natural, 591 Ml', 768.1);
insert into productos (nombre_producto, precio) values ('Kellogs Cereal In A Cup', 466.79);
insert into productos (nombre_producto, precio) values ('Beer - Sleemans Cream Ale', 168.98);
insert into productos (nombre_producto, precio) values ('Nut - Hazelnut, Whole', 513.03);
insert into productos (nombre_producto, precio) values ('Tea Leaves - Oolong', 63.04);
insert into productos (nombre_producto, precio) values ('Milk - Buttermilk', 198.76);
insert into productos (nombre_producto, precio) values ('Pasta - Lasagna, Dry', 613.65);
insert into productos (nombre_producto, precio) values ('Bread Country Roll', 349.54);
insert into productos (nombre_producto, precio) values ('Sproutsmustard Cress', 122.59);
insert into productos (nombre_producto, precio) values ('Kahlua', 573.51);
insert into productos (nombre_producto, precio) values ('Energy Drink - Franks Pineapple', 825.51);
insert into productos (nombre_producto, precio) values ('Doilies - 8, Paper', 105.25);
insert into productos (nombre_producto, precio) values ('Everfresh Products', 321.58);
insert into productos (nombre_producto, precio) values ('Leeks - Baby, White', 582.5);
insert into productos (nombre_producto, precio) values ('Pepper - Chili Powder', 510.1);
insert into productos (nombre_producto, precio) values ('Bread - Italian Roll With Herbs', 840.28);
insert into productos (nombre_producto, precio) values ('Cherries - Maraschino,jar', 281.34);
insert into productos (nombre_producto, precio) values ('Sauce Bbq Smokey', 921.98);
insert into productos (nombre_producto, precio) values ('Ham - Cooked', 46.73);
insert into productos (nombre_producto, precio) values ('Wine - Baron De Rothschild', 113.61);
insert into productos (nombre_producto, precio) values ('Glass - Wine, Plastic, Clear 5 Oz', 431.18);
insert into productos (nombre_producto, precio) values ('Pork - Shoulder', 729.13);
insert into productos (nombre_producto, precio) values ('Wine - Magnotta - Belpaese', 669.42);
insert into productos (nombre_producto, precio) values ('Pork - Loin, Bone - In', 550.14);
insert into productos (nombre_producto, precio) values ('Chocolate Bar - Oh Henry', 876.85);
insert into productos (nombre_producto, precio) values ('Tea - Vanilla Chai', 153.62);
insert into productos (nombre_producto, precio) values ('Chips Potato Swt Chilli Sour', 737.72);
insert into productos (nombre_producto, precio) values ('Miso - Soy Bean Paste', 737.84);
insert into productos (nombre_producto, precio) values ('Honey - Comb', 981.48);
insert into productos (nombre_producto, precio) values ('Ezy Change Mophandle', 852.66);
insert into productos (nombre_producto, precio) values ('Wine - Chateauneuf Du Pape', 503.11);
insert into productos (nombre_producto, precio) values ('Rum - Light, Captain Morgan', 92.64);
insert into productos (nombre_producto, precio) values ('Onion Powder', 297.57);
insert into productos (nombre_producto, precio) values ('Thyme - Lemon, Fresh', 674.0);
insert into productos (nombre_producto, precio) values ('Piping Jelly - All Colours', 624.3);
insert into productos (nombre_producto, precio) values ('Ham Black Forest', 280.38);
insert into productos (nombre_producto, precio) values ('Cookie Chocolate Chip With', 822.49);
insert into productos (nombre_producto, precio) values ('Corn - On The Cob', 317.19);
insert into productos (nombre_producto, precio) values ('Wasabi Paste', 110.64);
insert into productos (nombre_producto, precio) values ('Chicken - Diced, Cooked', 310.02);
insert into productos (nombre_producto, precio) values ('Pasta - Ravioli', 208.2);
insert into productos (nombre_producto, precio) values ('Squash - Butternut', 769.07);
insert into productos (nombre_producto, precio) values ('Napkin - Dinner, White', 978.58);
insert into productos (nombre_producto, precio) values ('Vodka - Hot, Lnferno', 372.83);
insert into productos (nombre_producto, precio) values ('Muffin - Blueberry Individual', 568.47);
insert into productos (nombre_producto, precio) values ('Pork - Liver', 42.0);
insert into productos (nombre_producto, precio) values ('Lettuce - Radicchio', 525.76);
insert into productos (nombre_producto, precio) values ('Steamers White', 849.81);
insert into productos (nombre_producto, precio) values ('Pie Shells 10', 515.13);
insert into productos (nombre_producto, precio) values ('Wine - Saint Emilion Calvet', 593.05);
insert into productos (nombre_producto, precio) values ('Beer - Sleemans Honey Brown', 382.4);
insert into productos (nombre_producto, precio) values ('Cod - Fillets', 449.49);
insert into productos (nombre_producto, precio) values ('Spice - Greek 1 Step', 490.74);
insert into productos (nombre_producto, precio) values ('Coffee - Decaffeinato Coffee', 871.51);
insert into productos (nombre_producto, precio) values ('Calypso - Lemonade', 799.16);
insert into productos (nombre_producto, precio) values ('Nantucket - Orange Mango Cktl', 951.28);
insert into productos (nombre_producto, precio) values ('Syrup - Kahlua Chocolate', 936.94);
insert into productos (nombre_producto, precio) values ('Cheese - Le Cheve Noir', 560.71);
insert into productos (nombre_producto, precio) values ('Tendrils - Baby Pea, Organic', 286.65);
insert into productos (nombre_producto, precio) values ('Glass Clear 7 Oz Xl', 151.19);
insert into productos (nombre_producto, precio) values ('Venison - Striploin', 588.86);
insert into productos (nombre_producto, precio) values ('Appetizer - Lobster Phyllo Roll', 687.73);
insert into productos (nombre_producto, precio) values ('Wine - Crozes Hermitage E.', 525.29);
insert into productos (nombre_producto, precio) values ('Lentils - Green, Dry', 883.1);
insert into productos (nombre_producto, precio) values ('Table Cloth 62x114 Colour', 333.42);
insert into productos (nombre_producto, precio) values ('Bread Fig And Almond', 253.19);
insert into productos (nombre_producto, precio) values ('Broom And Broom Rack White', 298.44);
insert into productos (nombre_producto, precio) values ('Grapefruit - Pink', 296.88);
insert into productos (nombre_producto, precio) values ('Tea - Orange Pekoe', 668.48);
insert into productos (nombre_producto, precio) values ('Cookie - Oreo 100x2', 394.65);
insert into productos (nombre_producto, precio) values ('Ecolab - Medallion', 892.41);
insert into productos (nombre_producto, precio) values ('Rootbeer', 971.11);
insert into productos (nombre_producto, precio) values ('Red Currants', 144.45);
insert into productos (nombre_producto, precio) values ('Wine - Dubouef Macon - Villages', 29.6);
insert into productos (nombre_producto, precio) values ('Spice - Peppercorn Melange', 108.32);
insert into productos (nombre_producto, precio) values ('Pasta - Penne Primavera, Single', 597.0);
insert into productos (nombre_producto, precio) values ('Energy - Boo - Koo', 740.13);
insert into productos (nombre_producto, precio) values ('Table Cloth 120 Round White', 4.21);
insert into productos (nombre_producto, precio) values ('Anchovy Fillets', 477.36);
insert into productos (nombre_producto, precio) values ('Tomatoes Tear Drop Yellow', 45.52);
insert into productos (nombre_producto, precio) values ('Veal - Brisket, Provimi, Bone - In', 757.22);
insert into productos (nombre_producto, precio) values ('Petit Baguette', 987.3);
insert into productos (nombre_producto, precio) values ('Spinach - Frozen', 610.55);
insert into productos (nombre_producto, precio) values ('Steampan Lid', 497.28);
insert into productos (nombre_producto, precio) values ('Paper Cocktail Umberlla 80 - 180', 284.18);
insert into productos (nombre_producto, precio) values ('Wine - Gato Negro Cabernet', 359.13);
insert into productos (nombre_producto, precio) values ('Foam Cup 6 Oz', 497.08);
insert into productos (nombre_producto, precio) values ('Baking Powder', 653.57);
insert into productos (nombre_producto, precio) values ('Pork - Bacon Cooked Slcd', 430.75);
insert into productos (nombre_producto, precio) values ('Jameson - Irish Whiskey', 41.72);
insert into productos (nombre_producto, precio) values ('Coffee - Cafe Moreno', 548.77);
insert into productos (nombre_producto, precio) values ('Pork - Bones', 888.25);
insert into productos (nombre_producto, precio) values ('Wine - Rioja Campo Viejo', 11.12);
insert into productos (nombre_producto, precio) values ('Lamb - Sausage Casings', 602.57);
insert into productos (nombre_producto, precio) values ('Propel Sport Drink', 694.11);
insert into productos (nombre_producto, precio) values ('Sage - Ground', 945.25);
insert into productos (nombre_producto, precio) values ('Bread - White Mini Epi', 691.0);
insert into productos (nombre_producto, precio) values ('Spinach - Packaged', 897.84);
insert into productos (nombre_producto, precio) values ('Tart - Butter Plain Squares', 796.77);
insert into productos (nombre_producto, precio) values ('Coffee - Ristretto Coffee Capsule', 538.98);
insert into productos (nombre_producto, precio) values ('Flour - Chickpea', 571.74);
insert into productos (nombre_producto, precio) values ('Wine - Charddonnay Errazuriz', 432.86);
insert into productos (nombre_producto, precio) values ('Nacho Chips', 629.61);
insert into productos (nombre_producto, precio) values ('Soup - Knorr, Chicken Gumbo', 887.56);
insert into productos (nombre_producto, precio) values ('Turkey - Ground. Lean', 706.16);
insert into productos (nombre_producto, precio) values ('Glaze - Clear', 158.15);
insert into productos (nombre_producto, precio) values ('Spring Roll Veg Mini', 891.92);
insert into productos (nombre_producto, precio) values ('Sour Puss Sour Apple', 731.14);
insert into productos (nombre_producto, precio) values ('Food Colouring - Red', 506.84);
insert into productos (nombre_producto, precio) values ('Mahi Mahi', 736.43);
insert into productos (nombre_producto, precio) values ('Puree - Pear', 260.38);
insert into productos (nombre_producto, precio) values ('Tart - Butter Plain Squares', 407.49);
insert into productos (nombre_producto, precio) values ('Oven Mitt - 13 Inch', 431.49);
insert into productos (nombre_producto, precio) values ('Flour - So Mix Cake White', 798.21);
insert into productos (nombre_producto, precio) values ('Wine - Montecillo Rioja Crianza', 846.1);
insert into productos (nombre_producto, precio) values ('Table Cloth 81x81 Colour', 918.43);
insert into productos (nombre_producto, precio) values ('Oil - Olive, Extra Virgin', 648.76);
insert into productos (nombre_producto, precio) values ('Mudslide', 844.25);
insert into productos (nombre_producto, precio) values ('Ecolab Crystal Fusion', 352.18);
insert into productos (nombre_producto, precio) values ('Knife Plastic - White', 912.74);
insert into productos (nombre_producto, precio) values ('Nut - Hazelnut, Ground, Natural', 21.17);
insert into productos (nombre_producto, precio) values ('Puff Pastry - Slab', 832.07);
insert into productos (nombre_producto, precio) values ('Muffin - Carrot Individual Wrap', 982.18);
insert into productos (nombre_producto, precio) values ('Instant Coffee', 571.12);
insert into productos (nombre_producto, precio) values ('Cheese - St. Paulin', 688.87);
insert into productos (nombre_producto, precio) values ('Water - Spring Water, 355 Ml', 915.57);
insert into productos (nombre_producto, precio) values ('Sherbet - Raspberry', 160.25);
insert into productos (nombre_producto, precio) values ('Dry Ice', 453.74);
insert into productos (nombre_producto, precio) values ('Wine - Dubouef Macon - Villages', 185.87);
insert into productos (nombre_producto, precio) values ('Lemonade - Kiwi, 591 Ml', 775.34);
insert into productos (nombre_producto, precio) values ('Monkfish Fresh - Skin Off', 980.94);
insert into productos (nombre_producto, precio) values ('Wine - Redchard Merritt', 309.32);
insert into productos (nombre_producto, precio) values ('Sauce - Oyster', 932.67);
insert into productos (nombre_producto, precio) values ('Papadam', 643.49);
insert into productos (nombre_producto, precio) values ('Brownies - Two Bite, Chocolate', 583.19);
insert into productos (nombre_producto, precio) values ('Lemon Pepper', 170.44);
insert into productos (nombre_producto, precio) values ('Shrimp - 16 - 20 Cooked, Peeled', 292.84);
insert into productos (nombre_producto, precio) values ('Table Cloth 54x54 Colour', 662.23);
insert into productos (nombre_producto, precio) values ('Yucca', 348.29);
insert into productos (nombre_producto, precio) values ('Sugar - Individual Portions', 452.0);
insert into productos (nombre_producto, precio) values ('Wine - Blue Nun Qualitatswein', 364.93);
insert into productos (nombre_producto, precio) values ('Turkey - Breast, Boneless Sk On', 774.38);
insert into productos (nombre_producto, precio) values ('Napkin Colour', 292.7);
insert into productos (nombre_producto, precio) values ('Coffee Cup 16oz Foam', 588.99);
insert into productos (nombre_producto, precio) values ('Lettuce - Lolla Rosa', 506.93);
insert into productos (nombre_producto, precio) values ('Beer - Tetleys', 946.86);
insert into productos (nombre_producto, precio) values ('Tea - Jasmin Green', 241.55);
insert into productos (nombre_producto, precio) values ('Broom - Corn', 915.03);
insert into productos (nombre_producto, precio) values ('Foam Cup 6 Oz', 958.12);
insert into productos (nombre_producto, precio) values ('Wine - Sake', 173.09);
insert into productos (nombre_producto, precio) values ('Smirnoff Green Apple Twist', 196.71);
insert into productos (nombre_producto, precio) values ('Lobster - Tail 6 Oz', 213.88);
insert into productos (nombre_producto, precio) values ('Beer - Mcauslan Apricot', 123.41);
insert into productos (nombre_producto, precio) values ('Buffalo - Striploin', 3.68);
insert into productos (nombre_producto, precio) values ('Tuna - Yellowfin', 179.68);
insert into productos (nombre_producto, precio) values ('Potatoes - Fingerling 4 Oz', 332.83);
insert into productos (nombre_producto, precio) values ('Creme De Cacao White', 170.98);
insert into productos (nombre_producto, precio) values ('Sambuca Cream', 132.72);
insert into productos (nombre_producto, precio) values ('Asparagus - White, Fresh', 880.57);
insert into productos (nombre_producto, precio) values ('Ketchup - Tomato', 574.89);
insert into productos (nombre_producto, precio) values ('Wine - White, Concha Y Toro', 740.54);
insert into productos (nombre_producto, precio) values ('Coffee - Frthy Coffee Crisp', 288.38);
insert into productos (nombre_producto, precio) values ('Nantucket Pine Orangebanana', 954.7);
insert into productos (nombre_producto, precio) values ('Chocolate Liqueur - Godet White', 918.46);
insert into productos (nombre_producto, precio) values ('Ice Cream Bar - Drumstick', 202.97);
insert into productos (nombre_producto, precio) values ('Chocolate - Dark Callets', 183.75);
insert into productos (nombre_producto, precio) values ('Foam Tray S2', 838.11);
insert into productos (nombre_producto, precio) values ('Lamb - Racks, Frenched', 230.57);
insert into productos (nombre_producto, precio) values ('Pastry - Banana Muffin - Mini', 263.88);
insert into productos (nombre_producto, precio) values ('Lettuce - Red Leaf', 626.71);
insert into productos (nombre_producto, precio) values ('External Supplier', 122.57);
insert into productos (nombre_producto, precio) values ('Pea - Snow', 517.12);
insert into productos (nombre_producto, precio) values ('Appetizer - Veg Assortment', 626.45);
insert into productos (nombre_producto, precio) values ('Muffin - Mix - Creme Brule 15l', 785.0);
insert into productos (nombre_producto, precio) values ('Ginsing - Fresh', 157.76);
insert into productos (nombre_producto, precio) values ('Vacuum Bags 12x16', 141.68);
insert into productos (nombre_producto, precio) values ('Chip - Potato Dill Pickle', 234.4);
insert into productos (nombre_producto, precio) values ('Energy Drink - Franks Original', 210.33);
insert into productos (nombre_producto, precio) values ('Chef Hat 20cm', 903.19);
insert into productos (nombre_producto, precio) values ('Lettuce - Treviso', 464.95);
insert into productos (nombre_producto, precio) values ('Wiberg Cure', 255.39);
insert into productos (nombre_producto, precio) values ('Cheese - Pont Couvert', 905.8);
insert into productos (nombre_producto, precio) values ('Coffee - Egg Nog Capuccino', 724.24);
insert into productos (nombre_producto, precio) values ('Rye Special Old', 3.13);
insert into productos (nombre_producto, precio) values ('Salsify, Organic', 560.58);
insert into productos (nombre_producto, precio) values ('Chocolate - Liqueur Cups With Foil', 163.12);
insert into productos (nombre_producto, precio) values ('Bread - Sour Batard', 124.26);
insert into productos (nombre_producto, precio) values ('Trueblue - Blueberry', 552.81);
insert into productos (nombre_producto, precio) values ('Pastry - Raisin Muffin - Mini', 107.21);
insert into productos (nombre_producto, precio) values ('Pork - Loin, Boneless', 992.74);
insert into productos (nombre_producto, precio) values ('Sauce - Oyster', 106.59);
insert into productos (nombre_producto, precio) values ('Capicola - Hot', 347.89);
insert into productos (nombre_producto, precio) values ('Coffee - Almond Amaretto', 520.04);
insert into productos (nombre_producto, precio) values ('Foam Dinner Plate', 219.84);
insert into productos (nombre_producto, precio) values ('Snapple - Mango Maddness', 192.84);
insert into productos (nombre_producto, precio) values ('Wine - White, Ej Gallo', 338.97);
insert into productos (nombre_producto, precio) values ('Bread - Pumpernickel', 925.46);
insert into productos (nombre_producto, precio) values ('Crab Meat Claw Pasteurise', 74.15);
insert into productos (nombre_producto, precio) values ('Pork - Hock And Feet Attached', 57.36);
insert into productos (nombre_producto, precio) values ('Curry Paste - Green Masala', 744.63);
insert into productos (nombre_producto, precio) values ('Soup - Verve - Chipotle Chicken', 884.66);
insert into productos (nombre_producto, precio) values ('Bread - Sour Batard', 143.66);
insert into productos (nombre_producto, precio) values ('Barley - Pearl', 737.88);
insert into productos (nombre_producto, precio) values ('Toothpick Frilled', 176.92);
insert into productos (nombre_producto, precio) values ('Dc Hikiage Hira Huba', 204.48);
insert into productos (nombre_producto, precio) values ('Tea - Green', 112.45);
insert into productos (nombre_producto, precio) values ('Pie Shell - 5', 545.08);
insert into productos (nombre_producto, precio) values ('Cheese - Cheddar With Claret', 168.32);
insert into productos (nombre_producto, precio) values ('Juice - Grape, White', 583.55);
insert into productos (nombre_producto, precio) values ('Nantucket - Carrot Orange', 23.55);
insert into productos (nombre_producto, precio) values ('Scrubbie - Scotchbrite Hand Pad', 722.34);
insert into productos (nombre_producto, precio) values ('Cod - Fillets', 800.56);
insert into productos (nombre_producto, precio) values ('Tuna - Yellowfin', 672.9);
insert into productos (nombre_producto, precio) values ('Garlic Powder', 873.31);
insert into productos (nombre_producto, precio) values ('Chocolate Bar - Reese Pieces', 910.49);
insert into productos (nombre_producto, precio) values ('Garam Masala Powder', 537.59);
insert into productos (nombre_producto, precio) values ('Lamb Rack - Ontario', 616.02);
insert into productos (nombre_producto, precio) values ('Lamb Tenderloin Nz Fr', 92.64);
insert into productos (nombre_producto, precio) values ('Turkey - Breast, Double', 462.48);
insert into productos (nombre_producto, precio) values ('Cheese - Camembert', 612.53);
insert into productos (nombre_producto, precio) values ('Coffee - French Vanilla Frothy', 237.71);
insert into productos (nombre_producto, precio) values ('Venison - Denver Leg Boneless', 483.33);
insert into productos (nombre_producto, precio) values ('Wine - Sake', 704.0);
insert into productos (nombre_producto, precio) values ('Lettuce Romaine Chopped', 286.26);
insert into productos (nombre_producto, precio) values ('Spic And Span All Purpose', 933.99);
insert into productos (nombre_producto, precio) values ('Ecolab - Lime - A - Way 4/4 L', 909.94);
insert into productos (nombre_producto, precio) values ('Shrimp - Black Tiger 13/15', 499.22);
insert into productos (nombre_producto, precio) values ('Wine - Touraine Azay - Le - Rideau', 517.86);
insert into productos (nombre_producto, precio) values ('Cloves - Ground', 158.17);
insert into productos (nombre_producto, precio) values ('Wine - Remy Pannier Rose', 712.35);
insert into productos (nombre_producto, precio) values ('Veal - Insides, Grains', 875.73);
insert into productos (nombre_producto, precio) values ('Asparagus - Green, Fresh', 995.91);
insert into productos (nombre_producto, precio) values ('Artichoke - Hearts, Canned', 268.44);
insert into productos (nombre_producto, precio) values ('Bagelers', 533.62);
insert into productos (nombre_producto, precio) values ('Table Cloth 54x54 White', 434.53);
insert into productos (nombre_producto, precio) values ('Pastry - Lemon Danish - Mini', 665.7);
insert into productos (nombre_producto, precio) values ('Salami - Genova', 879.68);
insert into productos (nombre_producto, precio) values ('Lidsoupcont Rp12dn', 399.19);
insert into productos (nombre_producto, precio) values ('Venison - Striploin', 941.37);
insert into productos (nombre_producto, precio) values ('Juice - Lagoon Mango', 136.33);
insert into productos (nombre_producto, precio) values ('Beer - Tetleys', 102.77);
insert into productos (nombre_producto, precio) values ('Wine - Manischewitz Concord', 966.87);
insert into productos (nombre_producto, precio) values ('Syrup - Monin, Amaretta', 231.43);
insert into productos (nombre_producto, precio) values ('Brandy - Bar', 38.02);
insert into productos (nombre_producto, precio) values ('Towel Dispenser', 893.16);
insert into productos (nombre_producto, precio) values ('Red Snapper - Fillet, Skin On', 729.63);
insert into productos (nombre_producto, precio) values ('Oil - Sesame', 449.88);
insert into productos (nombre_producto, precio) values ('Pimento - Canned', 917.0);
insert into productos (nombre_producto, precio) values ('Passion Fruit', 708.84);
insert into productos (nombre_producto, precio) values ('Chicken - Livers', 367.07);
insert into productos (nombre_producto, precio) values ('Lid Tray - 12in Dome', 987.57);
insert into productos (nombre_producto, precio) values ('Lamb Tenderloin Nz Fr', 284.86);
insert into productos (nombre_producto, precio) values ('Everfresh Products', 515.29);
insert into productos (nombre_producto, precio) values ('Catfish - Fillets', 66.46);
insert into productos (nombre_producto, precio) values ('Cattail Hearts', 878.24);
insert into productos (nombre_producto, precio) values ('Wine - Pinot Noir Latour', 585.62);
insert into productos (nombre_producto, precio) values ('Potatoes - Pei 10 Oz', 240.06);
insert into productos (nombre_producto, precio) values ('Nut - Walnut, Chopped', 888.42);
insert into productos (nombre_producto, precio) values ('Pastry - Key Limepoppy Seed Tea', 638.98);
insert into productos (nombre_producto, precio) values ('Bread - Multigrain Oval', 256.85);
insert into productos (nombre_producto, precio) values ('Pepper Squash', 378.18);
insert into productos (nombre_producto, precio) values ('Olives - Morracan Dired', 573.69);
insert into productos (nombre_producto, precio) values ('Hummus - Spread', 172.01);
insert into productos (nombre_producto, precio) values ('Squid - U - 10 Thailand', 299.23);
insert into productos (nombre_producto, precio) values ('Coffee - Colombian, Portioned', 343.33);
insert into productos (nombre_producto, precio) values ('Cookies Almond Hazelnut', 446.14);
insert into productos (nombre_producto, precio) values ('Pasta - Rotini, Colour, Dry', 8.34);
insert into productos (nombre_producto, precio) values ('Fork - Plastic', 897.64);
insert into productos (nombre_producto, precio) values ('Bread - Calabrese Baguette', 323.57);
insert into productos (nombre_producto, precio) values ('Bread - Granary Small Pull', 383.83);
insert into productos (nombre_producto, precio) values ('Potatoes - Mini White 3 Oz', 258.53);
insert into productos (nombre_producto, precio) values ('Soup - Campbells - Chicken Noodle', 77.56);
insert into productos (nombre_producto, precio) values ('Nut - Almond, Blanched, Sliced', 668.6);
insert into productos (nombre_producto, precio) values ('Crab - Claws, 26 - 30', 574.86);
insert into productos (nombre_producto, precio) values ('Chocolate Bar - Oh Henry', 889.25);
insert into productos (nombre_producto, precio) values ('Lychee - Canned', 366.43);
insert into productos (nombre_producto, precio) values ('Clams - Littleneck, Whole', 113.46);
insert into productos (nombre_producto, precio) values ('Coffee - Colombian, Portioned', 224.76);
insert into productos (nombre_producto, precio) values ('Gatorade - Orange', 899.12);
insert into productos (nombre_producto, precio) values ('Pickerel - Fillets', 338.91);
insert into productos (nombre_producto, precio) values ('Carrots - Mini, Stem On', 403.99);
insert into productos (nombre_producto, precio) values ('Wine - Red, Pinot Noir, Chateau', 812.47);
insert into productos (nombre_producto, precio) values ('Bread Ww Cluster', 977.03);
insert into productos (nombre_producto, precio) values ('Venison - Denver Leg Boneless', 442.43);
insert into productos (nombre_producto, precio) values ('Cherries - Frozen', 591.33);
insert into productos (nombre_producto, precio) values ('Smirnoff Green Apple Twist', 184.88);
insert into productos (nombre_producto, precio) values ('Salt And Pepper Mix - Black', 368.52);
insert into productos (nombre_producto, precio) values ('Towel - Roll White', 340.72);
insert into productos (nombre_producto, precio) values ('Capon - Breast, Double, Wing On', 193.26);
insert into productos (nombre_producto, precio) values ('Wine - Jaboulet Cotes Du Rhone', 230.94);
insert into productos (nombre_producto, precio) values ('Bowl 12 Oz - Showcase 92012', 69.08);
insert into productos (nombre_producto, precio) values ('C - Plus, Orange', 17.73);
insert into productos (nombre_producto, precio) values ('Goldschalger', 668.7);
insert into productos (nombre_producto, precio) values ('Foam Espresso Cup Plain White', 917.68);
insert into productos (nombre_producto, precio) values ('Cheese - Ricotta', 799.79);
insert into productos (nombre_producto, precio) values ('Mustard - Dry, Powder', 660.54);
insert into productos (nombre_producto, precio) values ('Caviar - Salmon', 238.69);
insert into productos (nombre_producto, precio) values ('Wine - Ej Gallo Sonoma', 148.2);
insert into productos (nombre_producto, precio) values ('Appetizer - Asian Shrimp Roll', 77.66);
insert into productos (nombre_producto, precio) values ('Wakami Seaweed', 727.01);
insert into productos (nombre_producto, precio) values ('Wine - Savigny - Les - Beaune', 970.96);
insert into productos (nombre_producto, precio) values ('Wine - Prosecco Valdobienne', 920.71);
insert into productos (nombre_producto, precio) values ('Thyme - Lemon, Fresh', 190.9);
insert into productos (nombre_producto, precio) values ('Sunflower Seed Raw', 681.01);
insert into productos (nombre_producto, precio) values ('Cheese Cheddar Processed', 246.95);
insert into productos (nombre_producto, precio) values ('Crab - Claws, 26 - 30', 195.51);
insert into productos (nombre_producto, precio) values ('Longos - Lasagna Beef', 380.91);
insert into productos (nombre_producto, precio) values ('Foil Cont Round', 926.67);
insert into productos (nombre_producto, precio) values ('Orange - Canned, Mandarin', 264.92);
insert into productos (nombre_producto, precio) values ('Cake - Box Window 10x10x2.5', 413.78);
insert into productos (nombre_producto, precio) values ('Nut - Almond, Blanched, Sliced', 299.83);
insert into productos (nombre_producto, precio) values ('Beer - Mill St Organic', 871.16);
insert into productos (nombre_producto, precio) values ('Pants Custom Dry Clean', 547.56);
insert into productos (nombre_producto, precio) values ('Wine - Red Oakridge Merlot', 717.8);
insert into productos (nombre_producto, precio) values ('Pastry - Mini French Pastries', 35.22);
insert into productos (nombre_producto, precio) values ('Wine - White, Schroder And Schyl', 133.8);
insert into productos (nombre_producto, precio) values ('Cheese - Grie Des Champ', 629.95);
insert into productos (nombre_producto, precio) values ('Sage - Rubbed', 255.77);
insert into productos (nombre_producto, precio) values ('Veal - Provimi Inside', 135.97);
insert into productos (nombre_producto, precio) values ('Sole - Dover, Whole, Fresh', 803.53);
insert into productos (nombre_producto, precio) values ('Sea Urchin', 784.07);
insert into productos (nombre_producto, precio) values ('Cleaner - Bleach', 364.53);
insert into productos (nombre_producto, precio) values ('Lamb - Ground', 488.32);
insert into productos (nombre_producto, precio) values ('Meldea Green Tea Liquor', 946.93);
insert into productos (nombre_producto, precio) values ('Soup - Campbells - Chicken Noodle', 471.57);
insert into productos (nombre_producto, precio) values ('Veal - Slab Bacon', 579.06);
insert into productos (nombre_producto, precio) values ('Dried Figs', 310.97);
insert into productos (nombre_producto, precio) values ('Bag Stand', 224.65);
insert into productos (nombre_producto, precio) values ('Chicken Giblets', 419.76);
insert into productos (nombre_producto, precio) values ('Spinach - Frozen', 734.19);
insert into productos (nombre_producto, precio) values ('Cheese - Woolwich Goat, Log', 877.67);
insert into productos (nombre_producto, precio) values ('Wine - Blue Nun Qualitatswein', 839.82);
insert into productos (nombre_producto, precio) values ('Sparkling Wine - Rose, Freixenet', 522.17);
insert into productos (nombre_producto, precio) values ('Wine - Mas Chicet Rose, Vintage', 661.81);
insert into productos (nombre_producto, precio) values ('Blackberries', 145.73);
insert into productos (nombre_producto, precio) values ('Sauce - Bernaise, Mix', 69.75);
insert into productos (nombre_producto, precio) values ('Wine - White, Ej', 676.81);
insert into productos (nombre_producto, precio) values ('Pepper - Red Bell', 940.99);
insert into productos (nombre_producto, precio) values ('Turkey - Breast, Double', 240.84);
insert into productos (nombre_producto, precio) values ('Squash - Acorn', 919.48);
insert into productos (nombre_producto, precio) values ('Island Oasis - Lemonade', 557.38);
insert into productos (nombre_producto, precio) values ('Bar - Sweet And Salty Chocolate', 194.64);
insert into productos (nombre_producto, precio) values ('Wine - Red, Cabernet Merlot', 791.29);
insert into productos (nombre_producto, precio) values ('Chicken - Whole Fryers', 892.87);
insert into productos (nombre_producto, precio) values ('Arrowroot', 954.5);
insert into productos (nombre_producto, precio) values ('Boogies', 482.78);
insert into productos (nombre_producto, precio) values ('Cheese - Gorgonzola', 166.78);
insert into productos (nombre_producto, precio) values ('Bagelers - Cinn / Brown Sugar', 107.0);
insert into productos (nombre_producto, precio) values ('Table Cloth 53x69 White', 197.31);
insert into productos (nombre_producto, precio) values ('Cheese - Romano, Grated', 694.61);
insert into productos (nombre_producto, precio) values ('Cheese - Marble', 173.45);
insert into productos (nombre_producto, precio) values ('Venison - Denver Leg Boneless', 925.8);
insert into productos (nombre_producto, precio) values ('Gingerale - Diet - Schweppes', 789.82);
insert into productos (nombre_producto, precio) values ('Beer - Creemore', 454.36);
insert into productos (nombre_producto, precio) values ('Kaffir Lime Leaves', 302.24);
insert into productos (nombre_producto, precio) values ('Cup - 3.5oz, Foam', 333.67);
insert into productos (nombre_producto, precio) values ('V8 - Vegetable Cocktail', 19.61);
insert into productos (nombre_producto, precio) values ('Irish Cream - Butterscotch', 943.17);
insert into productos (nombre_producto, precio) values ('Liqueur Banana, Ramazzotti', 145.83);
insert into productos (nombre_producto, precio) values ('Coriander - Seed', 912.1);
insert into productos (nombre_producto, precio) values ('Melon - Honey Dew', 885.21);
insert into productos (nombre_producto, precio) values ('Sweet Pea Sprouts', 949.22);
insert into productos (nombre_producto, precio) values ('Bamboo Shoots - Sliced', 499.5);
insert into productos (nombre_producto, precio) values ('Wakami Seaweed', 806.09);
insert into productos (nombre_producto, precio) values ('Rosemary - Primerba, Paste', 866.02);
insert into productos (nombre_producto, precio) values ('Tea Leaves - Oolong', 821.67);
insert into productos (nombre_producto, precio) values ('Salmon - Atlantic, Fresh, Whole', 254.25);
insert into productos (nombre_producto, precio) values ('Wine - Alicanca Vinho Verde', 720.51);
insert into productos (nombre_producto, precio) values ('Wine - Harrow Estates, Vidal', 906.8);
insert into productos (nombre_producto, precio) values ('Walkers Special Old Whiskey', 525.04);
insert into productos (nombre_producto, precio) values ('Tortillas - Flour, 10', 259.14);
insert into productos (nombre_producto, precio) values ('Pepsi - Diet, 355 Ml', 491.68);
insert into productos (nombre_producto, precio) values ('Tea - Honey Green Tea', 988.79);
insert into productos (nombre_producto, precio) values ('Carbonated Water - Wildberry', 589.13);
insert into productos (nombre_producto, precio) values ('Steampan Lid', 864.38);
insert into productos (nombre_producto, precio) values ('Lady Fingers', 755.09);
insert into productos (nombre_producto, precio) values ('Everfresh Products', 317.37);
insert into productos (nombre_producto, precio) values ('Ecolab - Lime - A - Way 4/4 L', 285.17);
insert into productos (nombre_producto, precio) values ('Bread - Flat Bread', 463.17);
insert into productos (nombre_producto, precio) values ('Cheese - Swiss', 344.76);
insert into productos (nombre_producto, precio) values ('Bay Leaf Ground', 829.3);
insert into productos (nombre_producto, precio) values ('Sprouts - Corn', 578.32);
insert into productos (nombre_producto, precio) values ('Lamb Leg - Bone - In Nz', 566.13);
insert into productos (nombre_producto, precio) values ('Cup - 8oz Coffee Perforated', 205.77);
insert into productos (nombre_producto, precio) values ('Mudslide', 363.13);
insert into productos (nombre_producto, precio) values ('Appetizer - Cheese Bites', 687.92);
insert into productos (nombre_producto, precio) values ('Tomatoes - Cherry, Yellow', 377.2);
insert into productos (nombre_producto, precio) values ('Melon - Watermelon, Seedless', 614.4);
insert into productos (nombre_producto, precio) values ('Lamb - Whole, Fresh', 847.25);
insert into productos (nombre_producto, precio) values ('Tomato - Plum With Basil', 130.56);
insert into productos (nombre_producto, precio) values ('Banana Turning', 865.27);
insert into productos (nombre_producto, precio) values ('Asparagus - Green, Fresh', 669.59);
insert into productos (nombre_producto, precio) values ('Corn - On The Cob', 384.2);
insert into productos (nombre_producto, precio) values ('Pasta - Orzo, Dry', 377.78);
insert into productos (nombre_producto, precio) values ('Bread - Petit Baguette', 684.77);
insert into productos (nombre_producto, precio) values ('Country Roll', 6.29);
insert into productos (nombre_producto, precio) values ('Cheese - Augre Des Champs', 782.9);
insert into productos (nombre_producto, precio) values ('Black Currants', 993.63);
insert into productos (nombre_producto, precio) values ('Neckerchief Blck', 534.36);
insert into productos (nombre_producto, precio) values ('Cheese - Asiago', 705.7);
insert into productos (nombre_producto, precio) values ('Table Cloth 62x120 White', 678.89);
insert into productos (nombre_producto, precio) values ('Beef - Montreal Smoked Brisket', 772.13);
insert into productos (nombre_producto, precio) values ('Foam Espresso Cup Plain White', 207.57);
insert into productos (nombre_producto, precio) values ('Jerusalem Artichoke', 555.91);
insert into productos (nombre_producto, precio) values ('Chips - Assorted', 400.98);
insert into productos (nombre_producto, precio) values ('Beef - Bones, Marrow', 692.92);
insert into productos (nombre_producto, precio) values ('Towels - Paper / Kraft', 666.57);
insert into productos (nombre_producto, precio) values ('Pork - Inside', 900.78);
insert into productos (nombre_producto, precio) values ('Gelatine Leaves - Bulk', 592.11);
insert into productos (nombre_producto, precio) values ('Emulsifier', 67.7);
insert into productos (nombre_producto, precio) values ('Cranberry Foccacia', 236.28);
insert into productos (nombre_producto, precio) values ('Syrup - Monin - Granny Smith', 780.12);
insert into productos (nombre_producto, precio) values ('Breakfast Quesadillas', 246.72);
insert into productos (nombre_producto, precio) values ('Sambuca - Opal Nera', 287.75);
insert into productos (nombre_producto, precio) values ('Cheese - Mix', 953.42);
insert into productos (nombre_producto, precio) values ('Ecolab - Balanced Fusion', 358.09);
insert into productos (nombre_producto, precio) values ('Gelatine Leaves - Bulk', 661.78);